### ISSUE TITLE
background thread issue and collectionview glitch on ios11 devices.

### ISSUE THREAD

**Issue by jadslim313** [badoo/Chatto#355]
I am running the example app. I have tried both the swift 4 and the swift 3 apps on the ios 11 iphone 7 device. They both run into the same issues.

Here is the error that is shown:

![screen shot 2017-08-28 at 2 45 19 pm](https://user-images.githubusercontent.com/12466304/29788146-93eb039a-8bff-11e7-901d-5e2e7e6d9e0b.png)

and here is the glitch:
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/12466304/29788386-680ae7da-8c00-11e7-920c-a6eac5a773aa.gif)

I don't know what to make of these errors

**Comment by jadslim313** [comment]
I'm using the swift4 branch

**Comment by AntonPalich** [comment]
@jadslim313 The fix is in master branch

**Comment by jadslim313** [comment]
will this fix be included in the swift4 version

**Comment by AntonPalich** [comment]
@jadslim313 I've merged master into swift4 branch. Please, check

**Comment by OneSman7** [comment]
using master. still getting thread issue
![2017-09-25 19 14 58](https://user-images.githubusercontent.com/4619076/30818971-e450b014-a225-11e7-9541-76b10ad2c00c.png)
![2017-09-25 19 15 10](https://user-images.githubusercontent.com/4619076/30818970-e44e5210-a225-11e7-9384-7b38d40dea20.png)
